#!/usr/bin/env node
"use strict"

var weekdays= ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

function week(now){
	now = new Date(now)
	now.setHours(0, 0, 0)
	var
	  year= new Date(now.getFullYear(), 0),
	  yearday= weekdays.indexOf(year.toString().substring(0,3)),
	  days= (now.getTime()- year.getTime()) / 1000. / 60. / 60. / 24.,
	  weeks= Math.floor((days + 6 - yearday) / 7.) // taken from the Monday
	if(yearday > 3){
		--weeks
	}
	return weeks
}

if(require.main === module){
	console.log(week())
}

module.exports= week
