#!/usr/bin/env node

var weekdays= ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

var
  now= new Date(),
  year= new Date(
	now.getFullYear(),
	0,
	0,
	now.getHours(),
	now.getMinutes(),
	now.getSeconds(),
	now.getMilliseconds()),
  yearday= weekdays.indexOf(year.toString().substring(0,3))

function week(){
	var
	  now= new Date(),
	  days= (now.getTime()- year.getTime()) / 1000. / 60. / 60. / 24.,
	  weeks= Math.floor((days + 6 - yearday) / 7.) // taken from the Monday
	if(yearday > 3){
		--weeks
	}
	return weeks
}

if(require.main === module){
	console.log(week)
}

module.exports= week
